### PR TITLE
added redis config options and trustedproxy for reverse proxy setups

### PR DESCRIPTION
**Pull request by MichaelErmer**

### CODE REVIEW

**Comment by MichaelErmer** [comment]
Ready to merge.

**Comment by leonjza** [comment]
I don't think we should add this to core. But, we *should* be adding an article about this in the [docs](https://github.com/eveseat/docs) for this!

**Comment by MichaelErmer** [comment]
Do you think it can be harmful to provide more optional config options?

you can just disable the trustproxy by default if you set it to 
    proxy => ''

**Comment by leonjza** [comment]
No it is probably not harmful. Its just adding an additional provider `Fideloper\Proxy\TrustedProxyServiceProvider` that is not commonly used, unessesarily increading overhead that is not needed. Ill suggest a PR to [docs](https://github.com/eveseat/docs) with the documentation about this though!

Thanks for the contribution though! 🎉

**Pull request closed without merging**
